server:  
  port: 8080
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
spring:  
  datasource:  
    url : jdbc:h2:mem:insurance  
    username : sa 
    password : mypass 
    driverClassName : org.h2.Driver
  jpa:  
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql : true  
    hibernate:  
      ddl-auto : update  
  h2:
    console:
      enabled: true