pipeline {
	// Pipeline execution time cannot exceed 30 minutes
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
	
	// Run pipeline on master node 
    agent {
      node {
        label 'master'
      }
    }

    stages {
		// Stage1 Show project
        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
		
		// Stage2 Show Hello
		stage('stage 2') {
			steps {
				sh 'echo hello from stage 2!'
			}
		}
		
		// Manual approval example
		stage('manual approval') {
			steps {
				timeout(time: 60, unit: 'MINUTES') {
					input message: "Move to stage 3?"
				}
			}
		}
		
		// Stage3 show pipeline end messages
        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
